services:
  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile

    container_name: ai-productivity-platform-api

    ports: 
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: unless-stopped

    depends_on:
      - rabbitmq



  

  rabbitmq:
    image: rabbitmq:3.13-management

    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: unless-stopped

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq



  
  celery:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile

    container_name: ai-productivity-platform-worker

    env_file:
      - .env

    volumes:
      - .:/app

    command: celery -A app.celery.celery_app:celery_app worker --loglevel=info

    restart: unless-stopped

    depends_on:
      - rabbitmq

    

    

volumes:
  rabbitmq_data: