"""Addition processing status to transcript.

Revision ID: 1dca2c4573a2
Revises: 72236b0d07c3
Create Date: 2026-07-14 04:44:32.001861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dca2c4573a2'
down_revision: Union[str, Sequence[str], None] = '72236b0d07c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('processing_status', sa.String(), nullable=False, server_default='PROCESSING'))
    op.add_column('transcripts', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('transcripts', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('transcripts', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'error_message')
    op.drop_column('transcripts', 'processing_completed_at')
    op.drop_column('transcripts', 'processing_started_at')
    op.drop_column('transcripts', 'processing_status')
    # ### end Alembic commands ###
