"""add User ID to transcript table

Revision ID: 72236b0d07c3
Revises: 29027f8a809c
Create Date: 2026-07-11 23:31:42.960416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72236b0d07c3'
down_revision: Union[str, Sequence[str], None] = '29027f8a809c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('transcripts', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'transcripts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_column('transcripts', 'user_id')
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
