"""addition of priority, category to todo database

Revision ID: 7e1a7423a064
Revises: d463e870d8f6
Create Date: 2026-07-09 05:03:06.750849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1a7423a064'
down_revision: Union[str, Sequence[str], None] = 'd463e870d8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('todos', 'category')
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
