"""add users table and user relationship

Revision ID: d463e870d8f6
Revises: fabbfc95d6f4
Create Date: 2026-07-07 03:25:12.911238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd463e870d8f6'
down_revision: Union[str, Sequence[str], None] = 'fabbfc95d6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cognito_sub', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub')
    )
    # Nullable so existing todos are preserved; application layer enforces user_id on new todos
    op.add_column('todos', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key('todos_user_id_fkey', 'todos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_user_id_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
